<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	
	<PropertyGroup>
		<CollectCoverage>true</CollectCoverage>
		<CoverletOutput>../coverage/projects/$(MSBuildProjectName)/</CoverletOutput>
		<CoverletOutputFormat>opencover</CoverletOutputFormat>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="bunit" />
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.msbuild">
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="GitHubActionsTestLogger">
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Moq" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3.mtp-v2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinanceManager.Api\FinanceManager.Api.csproj" />
		<ProjectReference Include="..\FinanceManager.Components\FinanceManager.Components.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
