<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<InternalsVisibleTo Include="FinanceManager.Tests.Integration" />
		<InternalsVisibleTo Include="FinanceManager.Tests.Unit" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Records\**" />
		<EmbeddedResource Remove="Records\**" />
		<None Remove="Records\**" />
	</ItemGroup>

</Project>