<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
		<WasmEnableHotReload>false</WasmEnableHotReload>
	  <UserSecretsId>dc6a3527-8cc4-4968-bc2c-e88cc40e7804</UserSecretsId>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\GlobalUsings.cs" Link="GlobalUsings.cs" />
	</ItemGroup>
	
	<ItemGroup>
		<InternalsVisibleTo Include="FinanceManager.Tests.Integration" />
		<InternalsVisibleTo Include="FinanceManager.Tests.Unit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\IMGS\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinanceManager.Components\FinanceManager.Components.csproj" />
	</ItemGroup>

</Project>