<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<NoWarn>$(NoWarn);CS0618;MUD0002;MUD0012</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="FinanceManager.IntegrationTests" />
		<InternalsVisibleTo Include="FinanceManager.UnitTests" />
	</ItemGroup>
	
	<ItemGroup>
		<Compile Include="..\GlobalUsings.cs" Link="GlobalUsings.cs" />
	</ItemGroup>
	
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Blazored.SessionStorage" />
		<PackageReference Include="Blazor-ApexCharts" />
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="MudBlazor" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="FinanceManager.IntegrationTests" />
		<InternalsVisibleTo Include="FinanceManager.UnitTests" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FinanceManager.Application\FinanceManager.Application.csproj" />
	</ItemGroup>

</Project>