using FinanceManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FinanceManager.Tests.Unit.Api.Migrations;

public class GiftCodeMigrationTests
{
    [Theory]
    [InlineData(false, "timestamp with time zone", "GENERATED BY DEFAULT AS IDENTITY", "character varying(64)")]
    [InlineData(true, "datetime2", "IDENTITY", "nvarchar(64)")]
    public void MigrationScript_UsesProviderColumnTypesAndGeneratedIds(bool sqlServer, string dateType, string identity, string hashType)
    {
        var options = new DbContextOptionsBuilder<AppDbContext>();
        if (sqlServer)
            options.UseSqlServer("Server=localhost;Database=script-only;Trusted_Connection=True", b => b.MigrationsAssembly("FinanceManager.Api"));
        else
            options.UseNpgsql("Host=localhost;Database=script-only", b => b.MigrationsAssembly("FinanceManager.Api"));
        using var context = new AppDbContext(options.Options);

        // SQL generation needs no running database and exercises the actual migration, including its target model.
        var script = context.GetService<IMigrator>().GenerateScript("AddCashAccountCurrency", "AddLifetimeGiftCodes");

        Assert.Contains("GiftCodes", script, StringComparison.Ordinal);
        Assert.Contains(dateType, script, StringComparison.Ordinal);
        Assert.Contains(identity, script, StringComparison.Ordinal);
        Assert.Contains(hashType, script, StringComparison.Ordinal);
        Assert.DoesNotContain(sqlServer ? "timestamp with time zone" : "nvarchar", script, StringComparison.Ordinal);
    }
}